# Generated by Django 6.0.2 on 2026-03-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.quantity')),
            ],
            options={
                'unique_together': {('product', 'quantity')},
            },
        ),
    ]
